import { Article } from "./article";

export const FEATURED_ARTICLE: Article = {
  id: 1,
  slug: "gta-vi-data-oficial-ia-generativa",
  title: "GTA VI finalmente tem data oficial: mundo aberto redefinido com IA generativa",
  excerpt:
    "Rockstar Games surpreende ao anunciar tecnologias inéditas que criam NPCs com memória persistente e narrativas dinâmicas — uma revolução no open world.",
  category: "Lançamentos",
  tag: "EXCLUSIVO",
  readTime: "6 min",
  timestamp: "Há 2 horas",
  image: "https://conectaja.proteste.org.br/wp-content/uploads/2025/05/trailer-gta6-970x472.png",
  isFeatured: true,
  isHot: true,
};

export const SECONDARY_ARTICLES: Article[] = [
  {
    id: 2,
    slug: "elden-ring-shadow-erdtree-12-milhoes",
    title: "Elden Ring: Shadow of the Erdtree bate 12 milhões de cópias em 48h",
    excerpt: "A expansão já é considerada o maior lançamento de DLC da história dos games.",
    category: "Vendas",
    tag: "BREAKING",
    readTime: "3 min",
    timestamp: "Há 4 horas",
    image:
      "https://s2-techtudo.glbimg.com/Ffvi3QbTnjwC1KFWnYChPVkBgnM=/0x0:1920x1080/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2022/m/a/d8M8EuSMCYmWSAiPz8bw/elden-ring-vendas.png",
    isHot: true,
  },
  {
    id: 3,
    slug: "ps6-confirmado-ray-tracing-nativo",
    title: "PS6 confirmado: Sony revela hardware com ray tracing em tempo real nativo",
    excerpt: "O próximo console da Sony promete eliminar completamente o rasterization.",
    category: "Hardware",
    tag: "REVELAÇÃO",
    readTime: "5 min",
    timestamp: "Há 6 horas",
    image: "https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=800&q=80",
  },
  {
    id: 4,
    slug: "hollow-knight-silksong-trailer-gameplay",
    title: "Hollow Knight: Silksong ganha novo trailer com 20 minutos de gameplay",
    excerpt: "Team Cherry quebra o silêncio e mostra mecânicas inéditas do aguardado sequel.",
    category: "Indie",
    tag: "GAMEPLAY",
    readTime: "4 min",
    timestamp: "Há 8 horas",
    image: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&q=80",
  },
];

export const TRENDING_ARTICLES: Article[] = [
  {
    id: 5,
    slug: "baldurs-gate-3-patch-final-1000-finais",
    title: "Baldur's Gate 3 recebe patch final com 1.000 finais alternativos",
    excerpt: "Larian Studios encerra suporte oficial com a maior atualização da história.",
    category: "RPG",
    tag: "UPDATE",
    readTime: "4 min",
    timestamp: "Há 10h",
    image: "https://images.unsplash.com/photo-1624555130581-1d9cca783bc0?w=600&q=80",
    score: 9.8,
  },
  {
    id: 6,
    slug: "microsoft-xbox-handheld-2025",
    title: "Microsoft confirma Xbox Handheld para o final de 2025",
    excerpt: "O portátil da Microsoft rodará jogos do Game Pass nativamente.",
    category: "Hardware",
    tag: "RUMOR",
    readTime: "3 min",
    timestamp: "Há 12h",
    image: "https://images.unsplash.com/photo-1585620385456-4759f9b5c7d9?w=600&q=80",
    score: 8.4,
  },
  {
    id: 7,
    slug: "cyberpunk-2077-ultrapassa-witcher-3-vendas",
    title: "Cyberpunk 2077 ultrapassa Witcher 3 em vendas totais",
    excerpt: "CD Projekt RED celebra a virada de imagem do jogo após anos de atualizações.",
    category: "Mercado",
    tag: "DADOS",
    readTime: "2 min",
    timestamp: "Há 14h",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&q=80",
    score: 9.1,
  },
  {
    id: 8,
    slug: "nintendo-switch-2-esgota-pre-venda-global",
    title: "Nintendo Switch 2 esgota em pré-venda global em 3 horas",
    excerpt: "Demanda supera qualquer lançamento anterior da Nintendo segundo analistas.",
    category: "Nintendo",
    tag: "LANÇAMENTO",
    readTime: "3 min",
    timestamp: "Há 1 dia",
    image: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=600&q=80",
    score: 9.5,
  },
];

export const REVIEW_ARTICLES: Article[] = [
  {
    id: 9,
    slug: "review-astro-bot",
    title: "Review: Astro Bot",
    excerpt: "A Team Asobi entrega a experiência mais pura e alegre dos games em anos.",
    category: "Review",
    tag: "NOTA 10",
    readTime: "8 min",
    timestamp: "Há 2 dias",
    image: "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=600&q=80",
    score: 10,
  },
  {
    id: 10,
    slug: "review-dragon-age-the-veilguard",
    title: "Review: Dragon Age: The Veilguard",
    excerpt: "BioWare tenta reencontrar sua identidade com resultados mistos.",
    category: "Review",
    tag: "NOTA 7",
    readTime: "10 min",
    timestamp: "Há 3 dias",
    image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&q=80",
    score: 7,
  },
  {
    id: 11,
    slug: "review-indiana-jones-and-the-great-circle",
    title: "Review: Indiana Jones and the Great Circle",
    excerpt: "MachineGames entrega o melhor jogo de Indiana Jones já feito.",
    category: "Review",
    tag: "NOTA 9",
    readTime: "9 min",
    timestamp: "Há 4 dias",
    image: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=600&q=80",
    score: 9,
  },
];
